server:
  port: 8751

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://admin:vsj555@localhost:8761/eureka/
#服务名称
spring:
  application:
    name: admin-service

  #mysql
  datasource:
    url: jdbc:mysql://172.16.0.20:3306/tests?useUnicode=true&useJDBCCompliantTimezoneShift=true&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: vsj_dev
    password: vsj555
    driver-class-name: com.mysql.jdbc.Driver

  #redis配置
  redis:
    database: 0
    host: 172.16.0.20
    port: 6379
    password: vsj555
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-waitMillis:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

#logback日志配置
logging:
  level:
    org.springframework.web: ERROR
  config: classpath:logback-spring.xml

# 启用mybatis自动映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#安全配置
#security:
#  #oauth2配置
#  oauth2:
#    resource:
#      filter-order: 3